INSERT INTO CONFIGURATION (ID, COMPANY_NAME, IS_GLOBAL_TENANT, KEY, NOTE, VALUE) VALUES (19, 'NTG', '1', 'LDAP_SEARCH_CONTROL_FOR_USER_NAME', 'Ldap search attrbuite for user name', 'userPrincipalName');

INSERT INTO CONFIGURATION (ID, COMPANY_NAME, IS_GLOBAL_TENANT, KEY, NOTE, VALUE) VALUES (20, 'NTG', '1', 'LDAP_SEARCH_CONTROL_FOR_FIRST_NAME', 'Ldap search attrbuite for first name', 'cn');

INSERT INTO CONFIGURATION (ID, COMPANY_NAME, IS_GLOBAL_TENANT, KEY, NOTE, VALUE) VALUES (21, 'NTG', '1', 'LDAP_SEARCH_CONTROL_FOR_LAST_NAME', 'Ldap search attrbuite for last name', 'sn');

INSERT INTO CONFIGURATION (ID, COMPANY_NAME, IS_GLOBAL_TENANT, KEY, NOTE, VALUE) VALUES (22, 'NTG', '1', 'LDAP_SEARCH_CONTROL_FOR_EMAIL', 'Ldap search attrbuite for email', 'mail');

INSERT INTO CONFIGURATION (ID, COMPANY_NAME, IS_GLOBAL_TENANT, KEY, NOTE, VALUE) VALUES (23, 'NTG', '1', 'LDAP_SEARCH_CONTROL_FOR_MOBILE', 'Ldap search attrbuite for mobile', 'mobile');

INSERT INTO CONFIGURATION (ID, COMPANY_NAME, IS_GLOBAL_TENANT, KEY, NOTE, VALUE) VALUES (24, 'NTG', '1', 'LDAP_SEARCH_CONTROL_FOR_GENDER', 'Ldap search attrbuite for gender', 'gender');

INSERT INTO CONFIGURATION (ID, COMPANY_NAME, IS_GLOBAL_TENANT, KEY, NOTE, VALUE) VALUES (25, 'NTG', '1', 'LDAP_SEARCH_CONTROL_FOR_LOCATION_NAME', 'Ldap search attrbuite for location name', 'company');

INSERT INTO CONFIGURATION (ID, COMPANY_NAME, IS_GLOBAL_TENANT, KEY, NOTE, VALUE) VALUES (26, 'NTG', '1', 'LDAP_SEARCH_CONTROL_FOR_EMAIL', 'Ldap search attrbuite for image', 'thumbnailPhoto');

UPDATE CONFIGURATION SET COMPANY_NAME = 'NTG', IS_GLOBAL_TENANT = '1', NOTE = 'The starting search point of LDAP server' WHERE KEY = 'BASE_DN';

UPDATE CONFIGURATION SET COMPANY_NAME = 'NTG', IS_GLOBAL_TENANT = '1'  WHERE  KEY = 'SERVER_ADMIN';

UPDATE CONFIGURATION SET COMPANY_NAME = 'NTG', IS_GLOBAL_TENANT = '1'  WHERE  KEY = 'SERVER_PASSWORD';
