INSERT INTO CONFIGURATION (ID, KEY, VALUE,NOTE) VALUES (7, 'PASS_ENC_METHOD', 'Blowfish','Encryption Method');
INSERT INTO CONFIGURATION (ID, KEY, VALUE,NOTE) VALUES (8, 'PASS_ENC_KEY', 'NTG1026_E','Encryption Key');
