INSERT INTO CONFIGURATION (ID, KEY, VALUE,NOTE) VALUES (9, 'MAX_FAILED_LOGIN', '3','Max User Failed Login Attempts');
INSERT INTO CONFIGURATION (ID, KEY, VALUE,NOTE) VALUES (10, 'MAX_TEMPORARY_LOCKS', '3','Max User Account Locks');
