package com.ntg.sadmin.constants;

public interface ConfigurationConstant {

    String DEFAULT_LOGIN_TYPE = "DEFAULT_LOGIN_TYPE";
    String LDAP_URL = "LDAP_URL";
    String LDAP_DOMAIN = "LDAP_DOMAIN";
    String LDAP_DEFAULT_GROUP = "LDAP_DEFAULT_GROUP";
    String MAIL_HOST = "MAIL_HOST";
    String MAIL_PORT = "MAIL_PORT";
    String MAIL_PORT_SSL = "MAIL_PORT_SSL";
    String MAIL_DOMAIN = "MAIL_DOMAIN";
    String PASS_ENC_METHOD = "PASS_ENC_METHOD";
    String PASS_ENC_KEY = "PASS_ENC_KEY";
    String MAX_FAILED_LOGIN = "MAX_FAILED_LOGIN";
    String MAX_TEMPORARY_LOCKS = "MAX_TEMPORARY_LOCKS";
    String LOCKING_TIME_IN_MINUTES = "LOCKING_TIME_IN_MINUTES";
    String BASE_DN = "BASE_DN";
    String SERVER_PASSWORD = "SERVER_PASSWORD";
    String SERVER_ADMIN = "SERVER_ADMIN";
    String LDAP_SEARCH_CONTROL_FOR_FIRST_NAME = "LDAP_SEARCH_CONTROL_FOR_FIRST_NAME";
    String LDAP_SEARCH_CONTROL_FOR_LAST_NAME = "LDAP_SEARCH_CONTROL_FOR_LAST_NAME";
    String LDAP_SEARCH_CONTROL_FOR_MOBILE = "LDAP_SEARCH_CONTROL_FOR_MOBILE";
    String LDAP_SEARCH_CONTROL_FOR_EMAIL = "LDAP_SEARCH_CONTROL_FOR_EMAIL";
    String LDAP_SEARCH_CONTROL_FOR_USER_NAME = "LDAP_SEARCH_CONTROL_FOR_USER_NAME";
    String LDAP_SEARCH_CONTROL_FOR_GENDER = "LDAP_SEARCH_CONTROL_FOR_GENDER";
    String LDAP_SEARCH_CONTROL_FOR_IMAGE = "LDAP_SEARCH_CONTROL_FOR_IMAGE";
    String LDAP_SEARCH_CONTROL_FOR_LOCATION_NAME = "LDAP_SEARCH_CONTROL_FOR_LOCATION_NAME";
    String LDAP_SEARCH_CONTROL_FOR_MANAGER = "LDAP_SEARCH_CONTROL_FOR_MANAGER";

}
